name = "Minecraft Modpack . Terr Firma Factions"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cbf1ffbc7e368e3b7cfb2afe772e62e1200db20b7b1497c38ebf9ec7b5046d65"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"

[options]
no-internal-hashes = true
