StartupEvents.registry('block', event => {
    event.create('terra:alexandriite_ore')
        .displayName('Alexandri’ite')
        .tagBlock('minecraft:mineable/pickaxe')
        .requiresTool(true)

    event.create('terra:alexandriite_crystal')
        .property(BlockProperties.FACING)
        .defaultState(state => state.set(BlockProperties.FACING, 'up'))
        .placementState(state => state.setValue(BlockProperties.FACING, state.clickedFace))
        .renderType('cutout')
        .notSolid()
        .displayName('Native Copper Crystal')

    event.create('terra:byzantium_ore')
        .displayName('Byzantium')
        .tagBlock('minecraft:mineable/pickaxe')
        .requiresTool(true)

    event.create('terra:byzantium_crystal')
        .property(BlockProperties.FACING)
        .defaultState(state => state.set(BlockProperties.FACING, 'up'))
        .placementState(state => state.setValue(BlockProperties.FACING, state.clickedFace))
        .renderType('cutout')
        .notSolid()
        .displayName('Cassiterite Crystal')

    event.create('terra:vitalum_ore')
        .displayName('Vitalum')
        .tagBlock('minecraft:mineable/pickaxe')
        .requiresTool(true)

    event.create('terra:vitalum_crystal')
        .property(BlockProperties.FACING)
        .defaultState(state => state.set(BlockProperties.FACING, 'up'))
        .placementState(state => state.setValue(BlockProperties.FACING, state.clickedFace))
        .renderType('cutout')
        .notSolid()
        .displayName('Sphalerite Crystal')

    event.create('terra:mugenium_ore')
        .displayName('Mugenium')
        .tagBlock('minecraft:mineable/pickaxe')
        .requiresTool(true)

    event.create('terra:mugenium_crystal')
        .property(BlockProperties.FACING)
        .defaultState(state => state.set(BlockProperties.FACING, 'up'))
        .placementState(state => state.setValue(BlockProperties.FACING, state.clickedFace))
        .renderType('cutout')
        .notSolid()
        .displayName('Bismuthinite Crystal')

    event.create('terra:antinomia_ore')
        .displayName('Antinomia')
        .tagBlock('minecraft:mineable/pickaxe')
        .requiresTool(true)

    event.create('terra:antinomia_crystal')
        .property(BlockProperties.FACING)
        .defaultState(state => state.set(BlockProperties.FACING, 'up'))
        .placementState(state => state.setValue(BlockProperties.FACING, state.clickedFace))
        .renderType('cutout')
        .notSolid()
        .displayName('Native Silver Crystal')

    event.create('terra:vutironium_ore')
        .displayName('Vutironium')
        .tagBlock('minecraft:mineable/pickaxe')
        .requiresTool(true)

    event.create('terra:vutironium_crystal')
        .property(BlockProperties.FACING)
        .defaultState(state => state.set(BlockProperties.FACING, 'up'))
        .placementState(state => state.setValue(BlockProperties.FACING, state.clickedFace))
        .renderType('cutout')
        .notSolid()
        .displayName('Native Gold Crystal')

    event.create('terra:durallium_ore')
        .displayName('Durallium')
        .tagBlock('minecraft:mineable/pickaxe')
        .requiresTool(true)

    event.create('terra:durallium_crystal')
        .property(BlockProperties.FACING)
        .defaultState(state => state.set(BlockProperties.FACING, 'up'))
        .placementState(state => state.setValue(BlockProperties.FACING, state.clickedFace))
        .renderType('cutout')
        .notSolid()
        .displayName('Hematite Crystal')
})